### Получить все сообщения
GET http://localhost:8080/messages/
Accept: application/json

### Отправить сообщение
POST http://localhost:8080/messages/
Content-type: application/json
Accept: application/json

{
    "text": "Hello world!"
}

### Получить сообщение с заданным id
GET http://localhost:8080/messages/1
Accept: application/json

### Заглушка в корне
GET http://localhost:8080/
Accept: application/json